<?php
session_start();
echo "<!DOCTYPE html>\n";
echo "<!--[if lt IE 7 ]><html class=\"ie ie6\" lang=\"en\"> <![endif]-->\n";
echo "<!--[if IE 7 ]><html class=\"ie ie7\" lang=\"en\"> <![endif]-->\n";
echo "<!--[if IE 8 ]><html class=\"ie ie8\" lang=\"en\"> <![endif]-->\n";
echo "<!--[if (gte IE 9)|!(IE)]><!-->\n";
echo "<html lang=\"en\" ng-app=\"myApp\">\n";
echo "<!--<![endif]-->\n";
echo "<!-- HEAD SECTION -->\n";
echo "<head>\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\n";
echo "    <meta name=\"description\" content=\"\">\n";
echo "    <meta name=\"author\" content=\"\">\n";
echo "    <!--[if IE]>\n";
echo "        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n";
echo "        <![endif]-->\n";
echo "    <title>MAK Issue Track</title>\n";
echo "    <!--GOOGLE FONT -->\n";
echo "    <link href=\'http://fonts.googleapis.com/css?family=Open+Sans\' rel=\'stylesheet\' type=\'text/css\'>\n";
echo "    <!--BOOTSTRAP MAIN STYLES -->\n";
echo "    <link href=\"assets/css/bootstrap.css\" rel=\"stylesheet\" />\n";
echo "    <!--FONTAWESOME MAIN STYLE -->\n";
echo "    <link href=\"assets/css/font-awesome.min.css\" rel=\"stylesheet\" />\n";
echo "    <!--CUSTOM STYLE -->\n";
echo "    <link href=\"assets/css/style.css\" rel=\"stylesheet\" />\n";
echo "    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\n";
echo "    <!--[if lt IE 9]>\n";
echo "      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n";
echo "      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js\"></script>\n";
echo "      <link rel=\"import\" href=\"noSignupNav.html\">\n";
echo "    <![endif]-->\n";
echo "</head>\n";
echo "    <!--END HEAD SECTION -->\n";
echo "<body ng-controller=\"tasksController\">\n";
echo "    <script type=\"text/javascript\" src=\"js/angular.min.js\"></script>\n";
echo "    <script type=\"text/javascript\" src=\"app/app.js\"></script>\n";
echo "    <!--NAV Section when signIn has not been done-->\n";
echo         (include('noSignupNav.html'));
echo "    <!--END NAV Section when signIn has not been done-->\n";
echo "     <!-- HEADER SECTION -->\n";
echo "    <div id=\"header-section\" >\n";
echo "          <div class=\"container\">\n";
echo "        \n";
echo "            <div class=\"row main-top-margin\">\n";
echo "                <div class=\"col-md-6 col-md-offset-3\">\n";
echo "                    <div class=\"text-center\">\n";
echo "                      \n";
echo "                          <i class=\"fa fa-briefcase main-icon\"></i>\n";
echo "                            <br />                            \n";
echo "                       \n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "                  <div class=\"row main-low-margin\">\n";
echo "                <div class=\"col-md-12\">\n";
echo "                    <div class=\"text-center\">\n";

            //retrieve session data
            if(isset($_SESSION['username'])){
echo        "Pageviews=". $_SESSION['username'];
//echo       "<meta http-equiv='refresh' content='0;url=index.html'>";
            }

echo "                        <h2 class=\"head-line\" >MAK ISSUE TRACK</h2>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "       \n";
echo "    </div> \n";
echo "      <!--END HEADER SECTION -->\n";
echo "   \n";
echo "     <!-- ABOUT SECTION -->\n";
echo "      <div id=\"about-section\" class=\"section\" >\n";
echo "        <div class=\"container\" >\n";
echo "          \n";
echo "               \n";
echo "            <div class=\"row main-low-margin\">\n";
echo "                <div class=\"col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1\" >\n";
echo "                    <h1>Our Profile</h1>\n";
echo "                    <h5>\n";
echo "                       Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n";
echo "                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.\n";
echo "                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n";
echo "                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n";
echo "                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.\n";
echo "                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.\n";
echo "                    </h5>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "           \n";
echo "            \n";
echo "        </div>\n";
echo "    </div>\n";
echo "    <div class=\"container\"  >\n";
echo "        <div class=\"row main-low-margin text-center\" >\n";
echo "                <div class=\"col-md-4 col-sm-4\" >\n";
echo "                    <i class=\"fa fa-flask fa-5x color-brown\"></i>\n";
echo "                    <h3>TESTED DESIGN</h3>\n";
echo "                    <p>\n";
echo "                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n";
echo "                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.\n";
echo "                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.\n";
echo "                    </p>\n";
echo "                </div>               \n";
echo "                    <div class=\"col-md-4 col-sm-4\" >\n";
echo "                    <i class=\"fa fa-pencil fa-5x color-blue\"></i>\n";
echo "                    <h3>EASY TO CUSTOMIZE</h3>\n";
echo "                    <p>\n";
echo "                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n";
echo "                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.\n";
echo "                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.\n";
echo "                    </p>\n";
echo "                </div>\n";
echo "                <div class=\"col-md-4 col-sm-4\" >\n";
echo "                    <i class=\"fa fa-thumbs-up fa-5x color-black\"></i>\n";
echo "                    <h3>WELL DOCUMENTED</h3>\n";
echo "                    <p>\n";
echo "                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n";
echo "                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.\n";
echo "                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.\n";
echo "                    </p>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "    </div>\n";
echo "    <div class=\"space-bottom\"></div>\n";
echo "        <!--END ABOUT SECTION -->\n";
echo "     <!--PARALLAX SECTION ONE-->\n";
echo "    <section id=\"story-freext\">\n";
echo "        <article>\n";
echo "       \n";
echo "                    <h3> <i class=\"fa fa-flask \"></i>  Lorem ipsum dolor sit amet</h3>\n";
echo "                   <span>\n";
echo "                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n";
echo "                        <br />\n";
echo "                         Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n";
echo "                    </span>\n";
echo "          \n";
echo "        </article>\n";
echo "        <div class=\"parallax\" data-velocity=\"-.3\" ></div>\n";
echo "    </section>\n";
echo "    <!-- END PARALLAX SECTION ONE -->\n";
echo "    <!--PRICE SECTION -->\n";
echo "       <div id=\"price-section\" class=\"section\" >\n";
echo "        <div class=\"container\" >\n";
echo "                         \n";
echo "            <div class=\"row main-low-margin\">\n";
echo "                <div class=\"col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1\" >\n";
echo "                    <h1>Pricing Details</h1>\n";
echo "                    <h5>\n";
echo "                       Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n";
echo "                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.\n";
echo "                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n";
echo "                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n";
echo "                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.\n";
echo "                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.\n";
echo "                    </h5>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "            \n";
echo "            \n";
echo "        </div>\n";
echo "    </div>\n";
echo "   \n";
echo "       <div class=\"container\" id=\"pricing-section\" >         \n";
echo "          \n";
echo "            <div class=\"main-low-margin col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 margin-top-100 \">\n";
echo "                    <div id=\"pricing-table\" class=\"row\">\n";
echo "                        <div class=\"col-md-4 col-sm-4\">\n";
echo "                            <ul class=\"plan-main\">\n";
echo "                                <li class=\"plan-name\">Starter</li>\n";
echo "                                <li class=\"plan-price\">$ 100</li>\n";
echo "                                <li>5GB Storage</li>\n";
echo "                                <li>1GB Space</li>\n";
echo "                                <li>200 Bandwidth</li>\n";
echo "                                <li>100 Email Address</li>\n";
echo "                                <li>24x7 Support</li>\n";
echo "                                <li>Live Chat</li>\n";
echo "                                <li class=\"plan-action\"><a href=\"#\" class=\"btn btn-primary btn-lg\">Signup</a></li>\n";
echo "                            </ul>\n";
echo "                        </div>\n";
echo "                        <div class=\"col-md-4 col-sm-4\" >\n";
echo "                            <ul class=\"plan-main featured active\">\n";
echo "                                <li class=\"plan-name\">Medium</li>\n";
echo "                                <li class=\"plan-price\">$ 200</li>\n";
echo "                                <li>5GB Storage</li>\n";
echo "                                <li>1GB Space</li>\n";
echo "                                <li>200 Bandwidth</li>\n";
echo "                                <li>100 Email Address</li>\n";
echo "                                <li>24x7 Support</li>\n";
echo "                                <li>Live Chat</li>\n";
echo "                                <li class=\"plan-action\"><a href=\"#\" class=\"btn btn-primary btn-lg\">Signup</a></li>\n";
echo "                            </ul>\n";
echo "                        </div>\n";
echo "                        <div class=\"col-md-4 col-sm-4\">\n";
echo "                            <ul class=\"plan-main\">\n";
echo "                                <li class=\"plan-name\">Advance</li>\n";
echo "                                <li class=\"plan-price\">$ 300</li>\n";
echo "                                <li>5GB Storage</li>\n";
echo "                                <li>1GB Space</li>\n";
echo "                                <li>200 Bandwidth</li>\n";
echo "                                <li>100 Email Address</li>\n";
echo "                                <li>24x7 Support</li>\n";
echo "                                <li>Live Chat</li>\n";
echo "                                <li class=\"plan-action\"><a href=\"#\" class=\"btn btn-primary btn-lg\">Signup</a></li>\n";
echo "                            </ul>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "             <!-- ./ Row Content-->\n";
echo "        </div>\n";
echo "      <div class=\"space-bottom\"></div>\n";
echo "    <!--END PRICE SECTION -->\n";
echo "     <!--PARALLAX SECTION TWO -->\n";
echo "         <section id=\"story-two\">\n";
echo "        <article >\n";
echo "         <h3> <i class=\"fa fa-desktop \"></i>  Lorem ipsum dolor sit amet</h3>\n";
echo "                    <span>\n";
echo "                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n";
echo "                        <br />\n";
echo "                         Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n";
echo "                    </span>\n";
echo "        </article>\n";
echo "         <div class=\"parallax\" data-velocity=\"-.1\"></div>\n";
echo "        <div class=\"parallax\" data-velocity=\"-.5\" data-fit=\"125\"></div>\n";
echo "    </section>\n";
echo "    <!--END PARALLAX SECTION TWO --> \n";
echo "    \n";
echo "    <!--CONTACT SECTION -->\n";
echo "     <div id=\"contact-section\" class=\"section\" >\n";
echo "        <div class=\"container\" >\n";
echo "          \n";
echo "               \n";
echo "            <div class=\"row main-low-margin\">\n";
echo "                <div class=\"col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1\" >\n";
echo "                    <h1>Contact Us </h1>\n";
echo "                    <h5>\n";
echo "                       Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n";
echo "                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.\n";
echo "                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n";
echo "                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n";
echo "                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.\n";
echo "                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.\n";
echo "                    </h5>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "         \n";
echo "            \n";
echo "        </div>\n";
echo "    </div>\n";
echo "     <div class=\"space-top\" id=\"contact-form\"></div>\n";
echo "        <div class=\"container\" >\n";
echo "                       <div class=\"row\">\n";
echo "                <div class=\"col-md-12  col-sm-12 \">\n";
echo "                    <div class=\"col-md-6  col-sm-12\" >\n";
echo "                        <h3>Physical Address</h3>\n";
echo "                        <hr />\n";
echo "                        <p>\n";
echo "                        ***, ********,<br />\n";
echo "                            München, Germany.<br />\n";
echo "                        Call: +49176416835*<br />\n";
echo "                        Email: demo@yourdomain.com<br />\n";
echo "                            </p>\n";
echo "                      \n";
echo "                    </div>\n";
echo "                    <div class=\"col-md-6  col-sm-12\" >\n";
echo "                        <h3>Need Help ? Write Us. </h3>\n";
echo "                        <hr />\n";
echo "                        <form>\n";
echo "                            <div class=\"row\">\n";
echo "                                <div class=\"col-md-6 col-sm-6\">\n";
echo "                                    <div class=\"form-group\">\n";
echo "                                        <input type=\"text\" class=\"form-control\" required=\"required\" placeholder=\"Name\">\n";
echo "                                    </div>\n";
echo "                                </div>\n";
echo "                                <div class=\"col-md-6 col-sm-6\">\n";
echo "                                    <div class=\"form-group\">\n";
echo "                                        <input type=\"text\" class=\"form-control\" required=\"required\" placeholder=\"Email address\">\n";
echo "                                    </div>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                            <div class=\"row\">\n";
echo "                                <div class=\"col-md-12 col-sm-12\">\n";
echo "                                    <div class=\"form-group\">\n";
echo "                                        <textarea name=\"message\" id=\"message\" required=\"required\" class=\"form-control\" rows=\"3\"  placeholder=\"Message\"></textarea>\n";
echo "                                    </div>\n";
echo "                                    <div class=\"form-group\">\n";
echo "                                        <button type=\"submit\" class=\"btn btn-primary\">Submit Request</button>\n";
echo "                                    </div>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                        </form>\n";
echo "                    </div>\n";
echo "                    \n";
echo "                </div>\n";
echo "            </div>\n";
echo "             <!-- ./ Row Content-->\n";
echo "        </div>\n";
echo "   <div class=\"space-top\"></div>\n";
echo "    <!--END CONTACT SECTION --> \n";
echo "      <!--FOOTER SECTION -->\n";
echo "    \n";
echo "      <div class=\"text-center\"  id=\"footer\" >\n";
echo "               \n";
echo "                      <a href=\"#\"><i class=\"fa fa-facebook-square fa-3x color-facebook\"></i></a>\n";
echo "                        <a href=\"#\"><i class=\"fa fa-twitter-square fa-3x color-twitter\"></i></a>\n";
echo "                        <a href=\"#\"><i class=\"fa fa-google-plus-square fa-3x color-google-plus\"></i></a>\n";
echo "                        <a href=\"#\"><i class=\"fa fa-linkedin-square fa-3x color-linkedin\"></i></a>\n";
echo "                        <a href=\"#\"><i class=\"fa fa-pinterest-square fa-3x color-pinterest\"></i></a>\n";
echo "          <br /><br />\n";
echo "         2014 www.yourdomain.com | All Right Reserved\n";
echo "         \n";
echo "            </div>\n";
echo "         \n";
echo "    <!--END FOOTER SECTION --> \n";
echo "    <!-- JAVASCRIPT FILES PLACED AT THE BOTTOM TO REDUCE THE LOADING TIME  -->\n";
echo "    <!-- CORE JQUERY LIBRARY -->\n";
echo "    <script src=\"assets/js/jquery.js\"></script>\n";
echo "    <!-- CORE BOOTSTRAP LIBRARY -->\n";
echo "    <script src=\"assets/js/bootstrap.min.js\"></script>\n";
echo "     <!-- PARALLAX SCRIPTS-->\n";
echo "     <script src=\"assets/js/scrolly-master/jquery.scrolly.js\"></script>\n";
echo "       <!-- CUSTOM SCRIPT-->  \n";
echo "    <script src=\"assets/js/custom.js\"></script>\n";
echo "    \n";
echo "</body>\n";
echo "</html>\n";
echo "\n";
exit();
?>